# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation

entry:
 path: /
 defaults:
  _controller: AppBundle:Default:entry
list:
 path: /display_cars
 defaults:
  _controller: AppBundle:Default:list
rent:
 path: /rent_car
 defaults:
  _controller: AppBundle:Default:rentForm
payment:
 path: /payment
 defaults:
  _controller: AppBundle:Default:processPayment
confirm_payment:
 path: /confirm_payment
 defaults:
  _controller: AppBundle:Default:confirmPayment