# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
 dataJSON:
  class: DataAPI\Infrastructure\DataFromJson
 data_service:
  class: DataAPI\Application\DataService
  arguments:
   - "@dataJSON"
 cars_service:
  class: DataAPI\Application\CarsService
  arguments:
   - "@data_service"
 users_service:
  class: DataAPI\Application\UsersService
  arguments:
   - "@data_service"
 form_service:
  class: CarRental\Application\RentFormService
  arguments:
   - "@users_service"
   - "@cars_service"
 payment_service:
  class: CarRental\Application\PaymentService
  arguments:
   - "@cars_service"